changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: Security
      labels: [security]
    - title: Added
      labels: [feature, enhancement]
    - title: Fixed
      labels: [bug, fix]
    - title: Documentation
      labels: [documentation]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
