# Generated by Django 4.1.5 on 2023-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=24, null=True)),
                ('password', models.CharField(blank=True, max_length=24, null=True)),
                ('matchPassword', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
    ]
