# Generated by Django 4.1.5 on 2023-04-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
